config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  root "texts#index"
  get "/texts/:id", to: "texts#show"
  resources :movies, only: [:index]

  resources :texts do
    resource :read_progresses, only: [:create, :destroy]
  end

  resources :movies do
    resource :watch_progresses, only: [:create, :destroy]
  end

  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :watch_progresses, dependent: :destroy

  RAILS_GENRE_LIST = %w[basic git ruby rails]
  validates :genre, :title, :url, presence: true
  enum genre: {
    invisible: 0,
    basic: 1,
    git: 2,
    ruby: 3,
    rails: 4,
    php: 5,
    html: 6,
    javascript: 7,
    typescript: 8,
    react: 9,
    vue: 10,
    angular: 11,
    aws: 12,
    money: 13,
    talk: 14,
    live: 15,
  }

  PHP_GENRE_LIST = %w[php]

  def watch_progressed_by?(user)
    watch_progresses.any? { |watch_progress| watch_progress.user_id == user.id }
  end

end

app/models/read_progress.rb
class ReadProgress < ApplicationRecord
  belongs_to :user
  belongs_to :text

  validates :user_id, uniqueness: {
                        scope: :text_id,
                        message: "は同じテキスト教材を2回以上読破済みにはできません",
                      }
end

app/models/text.rb
class Text < ApplicationRecord
  has_many :read_progresses, dependent: :destroy

  validates :genre, :title, :content, presence: true
  enum genre: {
    invisible: 0,
    basic: 1,
    git: 2,
    ruby: 3,
    rails: 4,
    php: 5,
    html: 6,
    javascript: 7,
    typescript: 8,
    react: 9,
    vue: 10,
    angular: 11,
    aws: 12,
    money: 13,
    talk: 14,
    live: 15,
  }
  RAILS_GENRE_LIST = %w[basic git ruby rails].freeze

  PHP_GENRE_LIST = %w[php].freeze

  def self.filter_by(genre)
    if genre == "php"
      Text.where(genre: Text::PHP_GENRE_LIST)
    else
      Text.where(genre: Text::RAILS_GENRE_LIST)
    end
  end

  def clicked_read_button?(user)
    read_progresses.exists?(user_id: user.id)
  end

  def self.left_join_read_texts(user_id)
    join_sql = <<~SQL.squish
      LEFT OUTER JOIN read_progresses ON read_progresses.text_id = texts.id
                                      AND read_progresses.user_id = #{user_id}
    SQL
    joins(join_sql)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :texts, dependent: :destroy
  has_many :read_progresses, dependent: :destroy
  has_many :watch_progresses, dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  def self.guest
    find_or_create_by!(email: "test@example.com") do |user|
      user.password = SecureRandom.urlsafe_base64
    end
  end
end

app/models/watch_progress.rb
class WatchProgress < ApplicationRecord
  belongs_to :user
  belongs_to :movie

  validates :user_id, uniqueness: {
                        scope: :movie_id,
                        message: "は同じ動画教材を2回以上読破済みにはできません",
                      }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  PER_PAGE = 12

  def index
    @movies = 
    if params[:genre] == "php"
      Movie.includes(:watch_progresses).where(genre: Movie::PHP_GENRE_LIST).page(params[:page]).per(PER_PAGE)
    else
      Movie.includes(:watch_progresses).where(genre: Movie::RAILS_GENRE_LIST).page(params[:page]).per(PER_PAGE)
    end
  end
end

app/controllers/read_progresses_controller.rb
class ReadProgressesController < ApplicationController
  def create
    @text = Text.find(params[:text_id])
    current_user.read_progresses.create!(text_id: params[:text_id])
  end

  def destroy
    @text = Text.find(params[:text_id])
    current_user.read_progresses.find_by(text_id: params[:text_id]).destroy!
  end
end

app/controllers/texts_controller.rb
class TextsController < ApplicationController
  def index
    select_sql = "texts.*, read_progresses.user_id = #{current_user.id} AS read"
    @texts = Text.includes(:read_progresses).left_join_read_texts(current_user.id).select(select_sql).order(:created_at).filter_by(params[:genre])
  end

  def show
    @text = Text.find(params[:id])
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def guest_sign_in
    # ゲストアカウントでログイン
    sign_in User.guest
    # トップページへリダイレクト
    redirect_to root_path, notice: "ゲストユーザーとしてログインしました。"
  end
end

app/controllers/watch_progresses_controller.rb
class WatchProgressesController < ApplicationController
  def create
    @movie = Movie.find(params[:movie_id])
    current_user.watch_progresses.create!(movie_id: @movie.id)
  end

  def destroy
    @movie = Movie.find(params[:movie_id])
    current_user.watch_progresses.find_by(movie_id: @movie.id).destroy!
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def max_width
    "mw-xl"
  end

  def text_title
    if params["genre"] == "php"
      "PHP テキスト教材"
    else
      "Ruby/Rails テキスト教材"
    end
  end
end

app/helpers/markdown_helper.rb
module MarkdownHelper
  def markdown(text)
    markdown = Redcarpet::Markdown.new(html_renderer, markdown_extensions)
    markdown.render(text).html_safe
  end

  private

  def html_renderer
      ::Coderayify.new(
      filter_html: true,
      hard_wrap: true,
      link_attributes: { rel: 'nofollow', target: "_blank" }
    )
  end

  def markdown_extensions
    {
      autolink: true,
      space_after_headers: true,
      no_intra_emphasis: true,
      fenced_code_blocks: true,
      tables: true,
      hard_wrap: true,
      xhtml: true,
      lax_html_blocks: true,
      strikethrough: true
    }
  end
end

app/helpers/movies_helper.rb
module MoviesHelper
  def embed_youtube(url)
    tag.iframe(
      src: url,
      frameborder: 0,
      allow: "accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture",
      allowfullscreen: true,
    )
  end
end

app/views/layouts/_flash.html.erb
<% flash.each do |flash_type, msg| %>
  <div class ="alert alert-<%= flash_type %>" role="alert">
    <a href="#" class="close" data-dismiss="alert">x</a>
    <%= msg %>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark">
  <%# <a class="navbar-brand" href="#">やんばるエキスパート</a> %>
  <%= link_to "やんばるエキスパート", root_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Ruby
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to "Ruby/Railsテキスト教材", texts_path, class: "dropdown-item" %>
          <%= link_to "Ruby/Rails動画教材", movies_path, class: "dropdown-item" %>
          <%# <a class="dropdown-item" href="#">AWSテキスト教材</a>
          <a class="dropdown-item" href="#">よくある質問集</a>
          <a class="dropdown-item" href="#">チャレンジ問題集</a> %>
        </div>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          PHP
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to "PHPテキスト教材", texts_path(genre: "php"), class: "dropdown-item" %>
          <%= link_to "PHP動画教材", movies_path(genre: "php"), class: "dropdown-item" %>
        </div>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link disabled" href="#">フロント</a>
        <div class="dropdown-menu">
          <%# <a class="dropdown-item" href="#">HTML&CSS</a>
          <a class="dropdown-item" href="#">JavaScript</a>
          <a class="dropdown-item" href="#">TypeScript</a>
          <a class="dropdown-item" href="#">Angular</a>
          <a class="dropdown-item" href="#">Vue</a> %>
        </div>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link disabled" href="#">デザイン講座</a>
        <div class="dropdown-menu">
          <%# <a class="dropdown-item" href="#">デザインツールの使い方</a>
          <a class="dropdown-item" href="#">実案件の取り方</a>
          <a class="dropdown-item" href="#">デザイナーのマーケティング戦略</a> %>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">勉強会</a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">マネタイズ講座</a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">LINE</a>
      </li>
      <% if user_signed_in? %>
        <!-- ログイン時 -->
        <li class="nav-item active">
          <%= link_to "アカウント編集", edit_user_registration_path, class: "nav-item nav-link active"%>
        </li>
        <li class="nav-item active">
          <%= link_to "ログアウト", destroy_user_session_path, class: "nav-item nav-link active", method: :delete, data: { confirm: "ログアウトしますか？" } %>
        </li>
      <% else %>
        <!-- 非ログイン時 -->
        <li class="nav-item active">
          <%= link_to "ログイン", new_user_session_path, class: "nav-item nav-link active" %>
        </li>
        <li class="nav-item active">
          <%= link_to "新規登録", new_user_registration_path, class: "nav-item nav-link active" %>
        </li>
        <li class="nav-item active">
          <%= link_to "ゲストログイン", users_guest_sign_in_path, method: :post, class: "nav-item nav-link active" %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>チーム開発 やんばるエキスパート教材クローン</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="bg-primary fixed-top">
      <%= render "layouts/header" %>
    </header>
    <main>
      <%# max_width メソッドは application_helper.rb に記載 %>
      <div class="base-container <%= max_width %>">
        <%= render "layouts/flash" %>
        <div class="container-fluid py-4 <%= devise_controller? ? 'mw-md' : 'mw-xl' %>">
        <%= yield %>
      </div>
    </main>
    <footer>
    </footer>
  </body>
</html>

app/views/movies/_diswatch.html.erb
<%= link_to "視聴済みにする", movie_watch_progresses_path(movie), class: "btn btn-secondary btn-block", method: :post, remote: true %>

app/views/movies/_movie.html.erb
<div class="card-box col-12 col-md-6 col-lg-4">
  <div class="card border-dark mb-3">
    <div class="YoutubeWrapper">
      <div class="embed-responsive embed-responsive-16by9">
        <%= embed_youtube(movie.url) %>
      </div>
    </div>
    <div class="card-body">
      <p id="movie-<%= movie.id %>">
        <% if movie.watch_progressed_by?(current_user) %>
          <%= render "watch", movie: movie %>
        <% else %>
          <%= render "diswatch", movie: movie %>
        <% end %>
      </p>
    </div>
    <h5 class="card-title">Lv.<%= movie_counter + @movies.offset_value + 1 %> : <%= movie.title %></h5>
  </div>
</div>

app/views/movies/_watch.html.erb
<%= link_to "視聴済みを解除", movie_watch_progresses_path(movie), class: "btn btn-primary btn-block", method: :delete, remote: true %>

app/views/movies/index.html.erb
<div class="text-center">
  <% if params[:genre] == "php" %>
    <h1>PHP動画</h1>
  <% else %>
    <h1>Ruby/Rails動画</h1>
  <% end %>
</div>  
<div class="movie-container">
  <div class="row">
    <%= render partial: "movie", collection: @movies %>
  </div>
</div>
<div class="pagination">
  <%= paginate @movies %>
</div>

app/views/read_progresses/create.js.erb
document.getElementById('text-<%= @text.id %>').innerHTML = '<%= j render("texts/read", text: @text) %>'

app/views/read_progresses/destroy.js.erb
document.getElementById('text-<%= @text.id %>').innerHTML = '<%= j render("texts/unread", text: @text) %>'

app/views/texts/_read.html.erb
<%# 「読破済みにする」の状態(クリックすると「読破済みを解除」になる) %>
<%= link_to "読破済みを解除", text_read_progresses_path(text), method: :delete, remote: true, class: 'btn btn-primary btn-block' %>

app/views/texts/_unread.html.erb
<%# 「読破済みを解除」の状態(クリックすると「読破済みにする」になる) %>
<%= link_to "読破済みにする", text_read_progresses_path(text), method: :post, remote: true, class: 'btn btn-secondary btn-block'%>

app/views/texts/index.html.erb
<div class="text-container">
  <h1 class="text-center">
    <%= text_title %>
  </h1>
  <div class="row">
    <% @texts.each do |text| %>
      <div class="card-box col-12 col-md-6 col-lg-4">
        <%= link_to "/texts/#{text.id}" do %>
          <div class="card border-dark mb-3">
            <div class="bd-placeholder-img card-img-top">
              <img class="text-card-img" src="https://d5izmuz0mcjzz.cloudfront.net/texts/no_image.jpg" alt="デフォルト画像">
            </div>
            <object class="read-button" id="text-<%= text.id %>">
              <%if text.read %>
                <%= render "read", text: text %>
              <% else %>
                <%= render "unread", text: text %>
              <% end %>
            </object>
            <div class="card-body">
              <h5 class="card-title"><%= text.title %></h5>
              <p class="card-genre">【<%= text.genre_i18n %>】</p>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/texts/show.html.erb
<h1><%= @text.title %></h1>
<p>
  <%= markdown(@text.content) %>
</p>

app/views/watch_progresses/create.js.erb
document.getElementById('movie-<%= @movie.id %>').innerHTML = '<%= j render("movies/watch", movie: @movie) %>'

app/views/watch_progresses/destroy.js.erb
document.getElementById('movie-<%= @movie.id %>').innerHTML = '<%= j render("movies/diswatch", movie: @movie) %>'